name: stands-bot

services:
  stands-bot-postgres:
    image: postgres:18-alpine
    restart: on-failure
    env_file:
      - ../.env
    volumes:
      - ./volumes/postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""]
      interval: 3s
      timeout: 3s
      retries: 10
    networks:
      - db

  stands-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: on-failure
    depends_on:
      stands-bot-postgres:
        condition: service_healthy
    env_file:
      - ../.env
    networks:
      - default
      - db

networks:
  default:
    name: mattermost_default
    external: true
  db:
    name: stands-bot-db
